---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-controller-manager
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-controller-manager
subjects:
- kind: ServiceAccount
  name: custom-controller-manager
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-controller-manager
  apiGroup: rbac.authorization.k8s.io
